### ISSUE TITLE
Python Django Tutorial: Full-Featured Web App Part 2

### ISSUE THREAD

**Issue by Hellrungj** [Hellrungj/Budget_Tracker#2]
## About
The project team needs to introduce to the Django framework. I have provided this video to tutorial watch below:  
[Python Django Tutorial: Full-Featured Web App Part 2 - Getting Started](https://www.https://www.youtube.com/watch?v=a48xeeo5Vnk&t=2s)

## Acceptance Criteria
- [x] Watch the video
- [x] Give some feedback or questions about the video in the comment section of the ticket

**Comment by mahkiwalker06** [comment]
so as I'm installing it on my computer, I'm running into some problems as far as finding the Path. I remember how to do it but it isn't showing me exactly where it is. However, I'm going to keep going and I will let you know if i found it. I was following along with the video too.

**Comment by mahkiwalker06** [comment]
link was broken sorry I forgot to tell you. I just subscribed to his channel. I find his tutorials useful and informative. I am seeing the diagrams more clearly. Now that I am watching the process. Its another thing I found daunting. I'm happy that it was addressed. I was worried I wouldn't pick it up. I think with more practice I can definitely do this. Sometimes with certain things I feel discouraged because I'm thinking so much about the end result of the project and psych myself out. that is my greatest downfall

**Comment by mahkiwalker06** [comment]
1. So what I am noticing is a lot of HTML being implemented within Django
2. I'm finding all the routes a bit difficult to follow(where to start and how to keep it going smooth)
3. I'm wondering how do you stay organized because flipping back and forth between files seems like it would get confusing
4. So you have to define the route by using the request in order to get the Path? Is there another way to get the path without backtracking?

-

**Comment by Hellrungj** [comment]
Great work!
